# Generated by Django 5.2.10 on 2026-01-27 17:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flower",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "price_amd",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "sale_price_amd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency", models.CharField(default="AMD", max_length=3)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=100)),
                ("colors", models.JSONField(default=list)),
                ("is_free_delivery", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "flowers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="flowers_categor_954839_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="flowers_is_acti_aedc35_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="flowers_created_29eda3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FlowerImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("is_main", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="flowers.flower",
                    ),
                ),
            ],
            options={
                "db_table": "flower_images",
                "ordering": ["-is_main", "created_at"],
            },
        ),
    ]
