# Generated by Django 4.2.11 on 2026-01-28 19:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Բնական գեղեցկություն', max_length=255)),
                ('subtitle', models.CharField(blank=True, default='Ձեր Հատուկ Պահերի', max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='Յուրաքանչյուր ծաղիկ պատմում է պատմություն։ Մենք ստեղծում ենք անմոռանալի պահեր թարմ և գեղեցիկ ծաղիկներով։', null=True)),
                ('special_offer', models.TextField(blank=True, default='Պատվիրեք հիմա և ստացեք 10% զեղչ Ձեր առաջին պատվերի համար հատուկ առաջարկ', null=True)),
                ('main_image', models.URLField(max_length=500)),
                ('extra_text', models.TextField(blank=True, help_text='Special writing here', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='flower',
            name='to_be_on_main_page',
            field=models.BooleanField(default=False),
        ),
    ]
