# Generated by Django 4.2.11 on 2026-01-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0003_mainpagecontent_flower_to_be_on_main_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagecontent',
            name='main_image',
            field=models.URLField(default='https://images.unsplash.com/photo-1767552670030-a276419d6d34?crop=entropy&cs=srgb&fm=jpg&q=85', max_length=500),
        ),
    ]
