# Generated by Django 4.2.11 on 2026-01-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0004_alter_mainpagecontent_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bacik_erktox',
            field=models.CharField(default='', max_length=100),
        ),
    ]
